#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xf9e5;
constexpr uint24_t FX_DATA_BYTES = 395819;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x018580;
  constexpr uint24_t SFX_Victory = 0x018624;
  constexpr uint24_t SFX_XPGain = 0x0186D8;
  constexpr uint24_t SFX_Three_Inc = 0x0186EC;
  constexpr uint24_t SFX_Three_Dec = 0x018708;
  constexpr uint24_t SFX_PlayerBlip = 0x018724;
  constexpr uint24_t SFX_EnemyBlip = 0x018734;
  constexpr uint24_t SFX_Explosion = 0x018744;
  constexpr uint24_t SFX_DoubleBeep = 0x018788;
  constexpr uint24_t SFX_DoubleBeepDown = 0x018798;
  constexpr uint24_t SFX_Bet1 = 0x0187A8;
  constexpr uint24_t SFX_Bet2 = 0x0187B0;
  constexpr uint24_t SFX_Bet3 = 0x0187B8;
  constexpr uint24_t SFX_Bet4 = 0x0187C0;
  constexpr uint24_t SFX_Bet5 = 0x0187C8;
  constexpr uint24_t SFX_Bet6 = 0x0187D0;
  constexpr uint24_t SFX_Click = 0x0187D8;
  constexpr uint24_t SFX_SmallBlind = 0x0187E0;
  constexpr uint24_t SFX_BigBlind = 0x0187E8;
}

namespace Constants
{
  constexpr uint24_t Starting_Bids = 0x0187F8;
  constexpr uint24_t Score_Panel_XTextPos = 0x0187FE;
  constexpr uint24_t Score_Panel_XPanelPos = 0x018804;
  constexpr uint24_t Score_Panel_Idx = 0x01880A;
}

namespace Images
{
  constexpr uint24_t Cards_Bottom = 0x018810;
  constexpr uint24_t Cards_Left = 0x01C9E2;
  constexpr uint24_t Cards_Right = 0x021DFC;
  constexpr uint24_t Hand_Left = 0x027216;
  constexpr uint24_t Hand_Right = 0x02788A;
  constexpr uint24_t Hand_Top = 0x027EFE;
  constexpr uint24_t Cards_Bottom_Grey = 0x028A16;
  constexpr uint24_t Cards_Left_Grey = 0x02CBE8;
  constexpr uint24_t Cards_Right_Grey = 0x032002;
  constexpr uint24_t PPOT = 0x03741C;
  constexpr uint24_t Sound_Volume_Grey = 0x03A41E;
  constexpr uint24_t Sound_Volume_White = 0x03AC60;
  constexpr uint24_t Sound_Checkbox = 0x03B4A2;
  constexpr uint24_t Title = 0x03B4B0;
  constexpr uint24_t HUD = 0x03F832;
  constexpr uint24_t Score_Numbers_Bottom = 0x03FA5C;
  constexpr uint24_t Score_Numbers_Left = 0x03FB5A;
  constexpr uint24_t Score_Numbers_Right = 0x03FC58;
  constexpr uint24_t Bid = 0x03FD56;
  constexpr uint24_t Numbers = 0x040724;
  constexpr uint24_t Numbers_3x5 = 0x040AE6;
  constexpr uint24_t Arrows = 0x04389C;
  constexpr uint24_t HighScores = 0x0438EC;
  constexpr uint24_t Dealer = 0x0442DE;
  constexpr uint24_t Hand_Full = 0x0442EF;
  constexpr uint24_t Rotate = 0x044381;
  constexpr uint24_t Flip = 0x04A8C3;
  constexpr uint24_t Fire = 0x04BAC5;
  constexpr uint24_t OhHell = 0x057AC7;
  constexpr uint24_t GameOver = 0x058BA9;
  constexpr uint24_t Instructions_01 = 0x0594C3;
  constexpr uint24_t Instructions_02 = 0x05B745;
  constexpr uint24_t Instructions_Arrows = 0x05D9C7;
  constexpr uint24_t Pause = 0x05DA29;
}

